export const intro = [
  {
    id: 'title',
    type: 'title',
    title: 'UptimeMonitor',
    subtitle: 'Hệ thống giám sát uptime tự động',
    meta: 'System Design — Go • gRPC • PostgreSQL • Redis • Temporal • Debezium • Traefik',
  },
  {
    id: 'agenda',
    type: 'list',
    title: 'Nội dung trình bày',
    items: [
      'Yêu cầu hệ thống',
      'Tech Stack & Kiến trúc microservices',
      'Topology dịch vụ',
      'Cơ sở dữ liệu',
      'Cơ chế điều độ (ZSET + Temporal)',
      'Các chức năng chính',
      'Auth & Bảo mật',
      'Deployment',
    ],
  },
  {
    id: 'requirements',
    type: 'section',
    title: 'Yêu cầu hệ thống',
    number: '01',
  },
  {
    id: 'func-req',
    type: 'requirements',
    title: 'Yêu cầu chức năng',
    func: [
      'Đăng ký / Đăng nhập tài khoản',
      'Quản lý server (CRUD)',
      'Cấu hình endpoint (URL, method, interval, timeout, expected code)',
      'Kiểm tra uptime tự động theo lịch',
      'Xem tỉ lệ uptime theo ngày (30 ngày gần nhất)',
      'Tìm kiếm server full-text',
      'Xuất / Nhập danh sách server từ Excel',
      'Cấu hình thông báo email',
      'Gửi báo cáo định kỳ qua email',
    ],
    nonfunc: [
      'Kiểm tra 10.000 endpoint với interval 30s',
      'Điều độ task tốt, CPU không spike',
      'Không N+1 query ở hầu hết route',
      'Phần lớn file ≤ 200 dòng',
      'Stateless, dễ scale (microservices)',
      'Code tổ chức tốt, dễ bảo trì',
      'Có logs cấu trúc + rotation',
    ],
  },
]
