export const intro = [
  {
    id: 'title',
    type: 'title',
    title: 'Server Management System',
    subtitle: 'Hệ thống quản lý server',
    meta: 'System Design — Go • gRPC • PostgreSQL • Traefik • Redis • Temporal • Debezium',
  },
  {
    id: 'agenda',
    type: 'list',
    title: 'Nội dung trình bày',
    items: [
      'Yêu cầu hệ thống',
      'Tech Stack & Kiến trúc microservices',
      'Cơ sở dữ liệu',
      'Tính năng & Quyết định thiết kế',
      'Deployment',
    ],
  },
  {
    id: 'requirements',
    type: 'section',
    title: 'Giới thiệu',
    number: '01',
  },
  {
    id: 'func-req',
    type: 'requirements',
    title: 'Yêu cầu chức năng',
    func: [
       'Đăng ký / Đăng nhập tài khoản bằng email (auth-service)',
       'Quản lý server (CRUD)',
       'Giám sát endpoint qua HTTP/DNS (URL, method, interval, timeout, expected_code)',
       'Kiểm tra trạng thái endpoint (HTTP/DNS) tự động theo lịch (interval cấu hình được)',
      'Xem tỉ lệ uptime theo ngày/khoảng thời gian',
      'Tìm kiếm server full-text',
      'Xuất / Nhập danh sách server từ Excel',
      'Cấu hình thông báo email',
      'Gửi báo cáo định kỳ qua email',
      'Gửi báo cáo chủ động (on-demand) không cần chờ lịch',
    ],
    nonfunc: [
      'Kiểm tra 10.000 server với interval 30s',
      'Điều độ task tốt, CPU không spike',
      'Không N+1 query ở hầu hết route',
      'Phần lớn file ≤ 200 dòng',
      'Stateless, dễ scale (microservices)',
      'Code tổ chức tốt, dễ bảo trì',
    ],
  },
]
